name: Coverage
on:
  push:
    branches:
      - "**"

env:
  VERSION: v2.27.0

jobs:
  coverage_and_integration_test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 9
      matrix:
        os: [ windows-latest, ubuntu-22.04 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download AntaresWeb asset from last release and unzip it
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.DAILY_CI }}
          REPO: AntaresSimulatorTeam/antares_desktop
          FILENAME: AntaresWeb-${{ matrix.os }}-${{ env.VERSION }}
        run: |
          bash scripts/find_release.sh $VERSION $FILENAME
          unzip -o $FILENAME -d ./AntaresWebDesktop

      - name: Set up Pythons
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox~=4.21.2
          pip install tox-uv~=1.11.3

      - name: Performs all tests on Windows
        if: matrix.os == 'windows-latest'
        run: tox -e windows

      - name: Performs coverage on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: tox -e coverage

      - name: Archive code coverage results
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: python-code-coverage-report
          path: coverage.xml

      - name: Download python coverage report
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/download-artifact@v4
        with:
          name: python-code-coverage-report

      - name: SonarCloud Scan
        if: matrix.os == 'ubuntu-22.04'
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
