name: Non regression API tests
on:
  schedule:
    - cron: '21 5 * * *'
  push:
    branches:
      - "**"


jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download AntaresWeb daily asset
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.DAILY_CI }}
          REPO: AntaresSimulatorTeam/antares_desktop
          VERSION: AntaresWebDev
        run: |
          bash scripts/find_release.sh $VERSION AntaresWeb

      - name: Unzip AntaresWebDesktop asset
        run: unzip -o AntaresWeb.zip -d AntaresWebDesktop

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Performs API integration test
        run: |
          pytest tests/integration/test_web_client.py
